### ISSUE TITLE
Upgrade go-redis/redis to v8 for context propagation

### ISSUE THREAD

**Issue by nachogoca** [signalfx/signalfx-go-tracing#135]
Currently the go-redis/redis wrapper inside the contrib directory is using the github.com/go-redis/redis version v6.15.7. This prevents me from using the latest capabilities introduced in v7 and v8 like context propagation.

https://github.com/signalfx/signalfx-go-tracing/blob/main/contrib/go-redis/redis/go.mod#L6

**Comment by nachogoca** [comment]
Can signalfx tracing be used with the out-of-the-box go-redis tracing? https://redis.uptrace.dev/tracing/

**Comment by pellared** [comment]
> Can signalfx tracing be used with the out-of-the-box go-redis tracing? https://redis.uptrace.dev/tracing/

Yes. It should be possible and this is the route I would advise. Right now we are putting a lot of effort to work with OpenTelemetry.

I do not know what is your use case, but take a look at least here:
- https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.opentelemetry.collector.html
- https://docs.splunk.com/Observability/get-started/migrate/migrate-to-otel.html

You can also take a look at https://github.com/signalfx/splunk-otel-go - it is BETA but should already be useable.

**Comment by nachogoca** [comment]
Thanks for the response. Ok, I will then use the OpenTelemetry library, thanks!
