### ISSUE TITLE
Issue with internal utils

### ISSUE THREAD

**Issue by ph4r5h4d** [signalfx/signalfx-go-tracing#136]
I'm trying to use the sample code with Echo 4 and I get the following error within my app:
```
sfx_test.go:13:2: use of internal package github.com/signalfx/signalfx-go-tracing/contrib/internal/testutil not allowed
```
I'm using Go 1.16 with Echo 4.2.2 and these are what I have for the SFX client:
```
github.com/signalfx/golib v2.4.0+incompatible
github.com/signalfx/signalfx-go-tracing v1.9.2
```

For the moment I can take the methods out and put them in my application package to make it work. But I also wonder am I doing something wrong? or the library needs an update!

**Comment by pellared** [comment]
Hello @ph4r5h4d 

Can you please provide more details?

I tried to reproduce the error, but for me, everything runs smoothly.
See: 
- branch on my repository where I was testing it: https://github.com/pellared/signalfx-go-tracing-test/tree/issue-136
- compatibility tests: https://github.com/pellared/signalfx-go-tracing-test/runs/2499957726

**Comment by ph4r5h4d** [comment]
It's weird, let me test it again.

**Comment by pellared** [comment]
@ph4r5h4d Any update?

**Comment by pellared** [comment]
No response. Closing
