### ISSUE TITLE
gomodule/redigo: want to add some customize span tag for redis such as db.name

### ISSUE THREAD

**Issue by xiaxiao-vungle** [signalfx/signalfx-go-tracing#156]
looks like it does not have the way to set the customized span tag outside the lib, is it OK to ask your team to help to update the lib to expose a way to set it? For example ,the net/http lib do have a way to set the customized span tag (https://github.com/signalfx/signalfx-go-tracing/blob/75290fe5aa940d0cdaea20ae9720dc9acdcb7c8b/contrib/net/http/option.go#L50)

**Comment by pellared** [comment]
Added in https://github.com/signalfx/signalfx-go-tracing/releases/tag/v1.10.0
