### ISSUE TITLE
Need to provide a way to stop generating stack trace when set tag error

### ISSUE THREAD

**Issue by yingchen0706v** [signalfx/signalfx-go-tracing#176]
When do APM tracing, we wrap http client by 
`httptrace.WrapClient()`
When there is error returned, it do stack tracing by https://github.com/signalfx/signalfx-go-tracing/blob/e54712655ee3919a9af1c0e9e843b49904f9c2f4/contrib/net/http/roundtripper.go#L35 
Need a way to disable stack tracking by 
`NoDebugStack()`

![Screen Shot 2021-09-13 at 4 35 28 PM](https://user-images.githubusercontent.com/49139592/133051471-0d9a85b3-021d-46da-853c-58081486e579.png)

**Comment by pellared** [comment]
Added in https://github.com/signalfx/signalfx-go-tracing/releases/tag/v1.12.0
