### ISSUE TITLE
resty with signal

### ISSUE THREAD

**Issue by dasuma** [signalfx/signalfx-go-tracing#201]
is it possible to have resty implemented with signalfx? to monitor calls between ms?

**Comment by pellared** [comment]
I see that `resty` supports setting a `http.RoundTripper` via https://pkg.go.dev/github.com/go-resty/resty/v2#Client.SetTransport. I think you can use [this](https://github.com/signalfx/signalfx-go-tracing/blob/e537a35bbe5cbc90cbbd2ef5fb2a9e1f7edaa57e/contrib/net/http/roundtripper.go#L68) function to wrap a RoundTripper (e.g. `http.DefaultTransport`)

**Comment by pellared** [comment]
@dasuma any update?

**Comment by dasuma** [comment]
yes, thanks
```
       client:=     resty.New(),
	roundTripper := httptrace.WrapRoundTripper(service.client.GetClient().Transport)
	client.SetTransport(roundTripper)
```
