### ISSUE TITLE
log trace_id?

### ISSUE THREAD

**Issue by dasuma** [signalfx/signalfx-go-tracing#203]
I am using gin, and I have added 
`router.Use(gintrace.Middleware("my-app")) `it works perfect.
but to find errors I would like to log the trace_id, how could I do it?

**Comment by pellared** [comment]
Take a look at https://github.com/signalfx/signalfx-go-tracing#inject-trace-context-in-http-requests for a similar example

**Comment by dasuma** [comment]
work perfect thanks

`func TraceIdFromCtx(ctx context.Context) (result string) {
	if span, ok := tracer.SpanFromContext(ctx); ok {
		result = tracer.TraceIDHex(span.Context())
	}
	return
}
traceID := signalfx.TraceIdFromCtx(param.Request.Context())
`
