### ISSUE TITLE
 c.FullPath undefined - Gin integration

### ISSUE THREAD

**Issue by mdsantosdev** [signalfx/signalfx-go-tracing#21]
➜  xxx git:(feature/signalfx-apm) ✗ go run main.go
 github.com/signalfx/signalfx-go-tracing/contrib/gin-gonic/gin
../../go/pkg/mod/github.com/signalfx/signalfx-go-tracing@v0.0.0-20190628184911-495bdb5772d8/contrib/gin-gonic/gin/gintrace.go:23:21: c.FullPath undefined (type *gin.Context has no field or method FullPath)

**Comment by tommynguyen-vungle** [comment]
Updating dependencies to latest version fixed it for me.
```
go get -u
```
