### ISSUE TITLE
Go tracing for auto instrumentation syntax 

### ISSUE THREAD

**Issue by markfstephens** [signalfx/signalfx-go-tracing#246]
The formatting for a colon delimiter between tags needs documented.

Example:
        - name: ENV_PLATFORM
            value: "gcp"
          - name: SIGNALFX_SPAN_TAGS
            value: "app_name:OnlineBoutique,app_id:1000"
          - name: NODE_IP
            valueFrom:
              fieldRef:
Note the colon : ,   equals = does not work

**Comment by pellared** [comment]
It looks to be documented. See https://github.com/signalfx/signalfx-go-tracing/#configuration-values (make sure to scroll the table to the right).

**Comment by markfstephens** [comment]
Thank you.  Sorry for not seeing on right
