### ISSUE TITLE
Out-of-date opentracing.Tracer Interface

### ISSUE THREAD

**Issue by ernatnav** [signalfx/signalfx-go-tracing#35]
When `ddtrace.GetGlobalTracer()` is called (e.g. inside ddtrace/tracer/span.go at line 85), it returns a `Tracer` interface with `Extract` and `Inject` methods that are missing a `format interface{}` parameter required by the opentracing-go 'Tracer' interface for the last two minor revisions (see opentracing-go/tracer.go line 111). This then causes a panic when the `GetGlobalTracer()` return is type asserted to the opentracing-go `Tracer` interface.

We are forced to pin our opentracing-go to a previous version in the meantime. (Not sure why they introduced a breaking change w/o a major version change).

<img width="812" alt="Screen Shot 2020-07-17 at 10 20 50 AM" src="https://user-images.githubusercontent.com/68437308/87808603-3d82b280-c817-11ea-9678-71168466f575.png">

**Comment by owais** [comment]
Turns out opentracing-go 1.2 introduced a change that ending up calling `span.Tracer()` method in one place. It never really worked but wasn't being called before. We've fixed the issue in `1.2.1` so upgrading to the latest version should resolve this.
